### ISSUE TITLE
example code crashes (incompatible shape)

### ISSUE THREAD

**Issue by damienchallet** [off99555/superkeras#7]
Hi,

Trying to run the untouched test-permutational-layer.ipynb, I have this error:

WARNING:tensorflow:Model was constructed with shape (None, 4) for input Tensor("x1_9:0", shape=(None, 4), dtype=float32), but it was called on an input with incompatible shape (None, 1, 4).
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-27-afbbc0dcc03a> in <module>
      2      [[4,3,2,1]],
      3      [[1,2,3,4]]]
----> 4 predictions = perm_layer.predict(x)

Thanks for any help

Damien

**Comment by off99555** [comment]
Hmm it's an old piece of code so not sure what was wrong. Have you tried running the permutational_layer.py itself?
You can run `python permutational_layer.py`.

**Comment by damienchallet** [comment]
unfortunately,

python -m superkeras.permutational_layer superkeras/permutational_layer.py

leads to the same error

WARNING:tensorflow:Model was constructed with shape (None, 4) for input
Tensor("x1_1:0", shape=(None, 4), dtype=float32), but it was called on an
input with incompatible shape (None, 1, 4).
Traceback (most recent call last):

**Comment by off99555** [comment]
I've found that it's the problem of new tensorflow version that unwillingly convert the entire list to a numpy array. Previously only each element inside the list will be converted to arrays but now they have changed its behavior. So I just fixed it by converting each element to an array manually so it should work now. You can check in the latest commit https://github.com/off99555/superkeras/commit/bda2d3057a929436d63bfb9c58f8df9abc7b2a5a by pulling from the main branch again. Let me know if it works.

**Comment by damienchallet** [comment]
Many thanks for your quick fix. It does work for me!
